name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            mkdir /home/ubuntu/front
            cd  /home/ubuntu/front
            git https://github.com/AymanAhmedOsman/ABI-Frontend.git
            # Add your deployment commands here
            # Example: scp -r ./dist/* user@server:/path/to/deployment/
            # Example: ssh user@server 'bash -s' < deploy.sh
